# Generated by Django 5.0.1 on 2024-01-28 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        ('Ranks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='Badge_img')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('subscriber', 'Subscriber'), ('moderator', 'Moderator')], default='regular', max_length=20)),
                ('tel', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('pfp', models.ImageField(default='default_user_image.png', upload_to='user_images')),
                ('bio', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('points', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(to='Users.badge')),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='Courses.course')),
                ('rank', models.ManyToManyField(to='Ranks.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('profit', 'Profit'), ('loss', 'Loss')], max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('img', models.ImageField(null=True, upload_to='user_transactions')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Users.customuser')),
            ],
        ),
    ]
