# Generated by Django 5.0.2 on 2024-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_added_points_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
