# Generated by Django 5.0.1 on 2024-01-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('none', 'None'), ('tshirt', 'T-Shirt'), ('cap', 'Cap'), ('cup', 'Cup')], default='regular', max_length=20)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Users.customuser')),
            ],
        ),
    ]
