# Generated by Django 5.0.2 on 2024-02-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_professor'),
        ('Users', '0007_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.level')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customuser')),
            ],
        ),
    ]
