# Generated by Django 5.0.2 on 2024-02-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_levelprogression'),
        ('Users', '0007_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customuser')),
            ],
        ),
    ]
