# Generated by Django 5.0.2 on 2024-02-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_courseprogression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='progression',
        ),
    ]
