# Generated by Django 5.0.2 on 2024-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_remove_level_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='levels_images'),
        ),
    ]
