# Generated by Django 5.0.2 on 2024-02-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_level_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='level',
            new_name='module',
        ),
    ]
