# Generated by Django 5.0.2 on 2024-02-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_rename_level_video_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.level')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.module'),
        ),
    ]
