# Generated by Django 5.0.2 on 2024-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_module_alter_video_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
