# Generated by Django 5.0.1 on 2024-01-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('schedule', models.DateTimeField()),
                ('Duration', models.DurationField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_private_sessions', to='Users.customuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_private_sessions', to='Users.customuser')),
            ],
        ),
    ]
